name: KMP library compilation check

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cocoapods install
        run: (cd sample/ios-app && pod install)
      - name: Check build
        run: ./gradlew build
      - name: Check plugin publication
        run: ./gradlew -p plugin publishToMavenLocal
      - name: Check runtime publication
        run: ./gradlew publishToMavenLocal