name: KMP library publish production version

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cocoapods install
        run: (cd sample/ios-app && pod install)
      - name: Plugin publication
        run: |
          ./gradlew -p plugin \
          publishNoValidationToBintray \
          -DBINTRAY_USER=${{ secrets.BINTRAY_USER }} -DBINTRAY_KEY=${{ secrets.BINTRAY_KEY }} \
          --stacktrace
      - name: Runtime publication
        run: |
          ./gradlew \
          publishNoValidationToBintray \
          -DBINTRAY_USER=${{ secrets.BINTRAY_USER }} -DBINTRAY_KEY=${{ secrets.BINTRAY_KEY }} \
          --stacktrace
